version: '3.8'
services:

  db:
    build:
      context: ./docker/db
    restart: always
    environment:
      - MYSQL_HOST= ${MYSQL_HOST}
      - MYSQL_USER= ${MYSQL_USER}
      - MYSQL_PASSWORD= ${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD= ${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE= ${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      -"3306:3306"


  node-service:
    build: 
      context: ./docker/api
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST= ${DB_HOST}
      - DB_USERNAME= ${DB_USERNAME}
      - DB_PASSWORD= ${DB_PASSWORD}
      - DB_ROOT_PASSWORD= ${DB_ROOT_PASSWORD}
      - DB_DATABASE= ${DB_DATABASE}
    ports:
      - "3000"

  nginx:
    build: 
      context: ./docker/nginx
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - node-service
volumes:
  db-data:

    
  

