version: '3.8'
services:
  api:
    build: ./docker/api
  db:
    build: ./docker/db
    image: mariadb
    env_file:
      - variable.env
    environment:
      - MYSQL_DATABASE=your_database_name
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
      - MYSQL_ROOT_PASSWORD=your_root_password
      - DB_HOST=db
      - DB_USERNAME=your_user
      - DB_PASSWORD=your_password
      - DB_DATABASE=your_database_name
    ports:
      - "3307:3306"
  
  node-service:
    build: ./docker/api
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  nginx:
    build: ./docker/nginx
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-service
