version: '3.8'
services:
  nginx:
    build: 
      context: ./docker/nginx
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - node-service
    
  db:
    build:
      context: ./docker/db
    restart: always
    environment:
      - MYSQL_HOST= ${MYSQL_HOST}
      - MYSQL_USER= ${MYSQL_USER}
      - MYSQL_PASSWORD= ${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD= ${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE= ${MYSQL_DATABASE}

  node-service:
    build: 
      context: ./docker/api
    depends_on:
      - db
    environment:
      - DB_HOST= ${DB_HOST}
      - DB_USERNAME= ${DB_USERNAME}
      - DB_PASSWORD= ${DB_PASSWORD}
      - DB_ROOT_PASSWORD= ${DB_ROOT_PASSWORD}
      - DB_DATABASE= ${DB_DATABASE}
    ports:
      - "3000"

    
  

