# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy the contents of the public folder into the Nginx server directory
COPY ./public /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80
