version: '3.8'
services:

  nginx:
    build: ./docker/nginx
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-service

  api:
    build: ./docker/api
  db:
    build: ./docker/db/init
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE= books
      - MYSQL_USER= user
      - MYSQL_PASSWORD= password
      - MYSQL_ROOT_PASSWORD= password
      
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d    
    ports:
      - "3307:3306"
  
  node-service:
    build: ./docker/api
    environment:
      DB_HOST: db
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: books
    ports:
      - "3000:3000"
    depends_on:
      - db
  

